-- DML
-- SELECT, INSERT, UPDATE, DELETE

SELECT CURRENT_TIMESTAMP FROM DUAL;

CREATE SEQUENCE SEQ_PARENT;
CREATE TABLE TBL_PARENT(
	ID NUMBER CONSTRAINT PK_PARENT PRIMARY KEY,
	PARENT_NAME VARCHAR2(255),
	PARENT_AGE NUMBER,
	PARENT_ADDRESS VARCHAR(255),
	PARENT_PHONE VARCHAR2(255),
	PARENT_GENDER CHAR(10)
);

INSERT INTO TBL_PARENT
VALUES(SEQ_PARENT.NEXTVAL, '홍길동', 20, '경기도 구리', '01001000100', '남');

INSERT INTO TBL_PARENT(ID, PARENT_NAME, PARENT_PHONE)
VALUES(SEQ_PARENT.NEXTVAL, '홍길동', '01012341234');


SELECT * FROM TBL_PARENT;