
CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
	USER_PASSWORD VARCHAR2(255) NOT NULL,
	USER_ADDRESS VARCHAR2(255),
	USER_BIRTH DATE
);

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL,
	POST_CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	USER_ID NUMBER,
	CONSTRAINT FK_POST_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_USER(ID)
);

CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR(255) NOT NULL,
	USER_ID NUMBER,
	POST_ID NUMBER,
	CONSTRAINT FK_REPLY_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_USER(ID),	
	CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
	REFERENCES TBL_POST(ID)
);

INSERT INTO TBL_USER 
VALUES(SEQ_USER.NEXTVAL, 'TPGUS', '1234', '경기도 구리시', '2000-05-15');
INSERT INTO TBL_USER 
VALUES(SEQ_USER.NEXTVAL, 'hgd4567', '9999', '서울시 용산구', '2001-07-07');
INSERT INTO TBL_USER 
VALUES(SEQ_USER.NEXTVAL, 'lss7890', '0000', '경기도 용인시', '1985-05-05');
INSERT INTO TBL_USER 
VALUES(SEQ_USER.NEXTVAL, 'jjy0001', '0001', '서울시 송파구', '1998-12-11');

INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT , USER_ID)
VALUES(SEQ_POST.NEXTVAL, '내 및으로 다 따라와 -김동건-', '미안해~', 4);

INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT , USER_ID)
VALUES(SEQ_POST.NEXTVAL, '나 장재영 탈주닌자', '장타치!', 4);

INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT , USER_ID)
VALUES(SEQ_POST.NEXTVAL, '겸손을 모르는 남자 박세현', '코딩은 나의 삶', 2);

INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT , USER_ID)
VALUES(SEQ_POST.NEXTVAL, '김영수 관종', '사람을 화나게 하는 법', 1);

INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT , USER_ID)
VALUES(SEQ_POST.NEXTVAL, '사실은 공짜가 아니었어 -장덕준-', '카카오 뱅크 110-0002-1112', 3);

INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT , USER_ID)
VALUES(SEQ_POST.NEXTVAL, '서서 밀면? 서민아', '재영이 1조인척한다', 2);

SELECT *
FROM TBL_POST;

-- 댓글(CONTENT, USER_ID, POST_ID)
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '너나 잘해 -박세현-', 3, 1);

INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '500원 내놔 -김영수-', 2, 1);

INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '내일 아침 커피 네가 사!', 2, 3);

INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '장타치! 상타치!', 1, 2);

INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '인정!', 1, 4);

INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '모른척~ ', 4, 5);

INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, 'SQLD 합격기원!', 3, 6);

SELECT *
FROM TBL_REPLY;

SELECT * 
FROM TBL_POST;

-- UPDATE ~ SET
UPDATE TBL_POST
SET POST_CONTENT = '다 덤벼!'
WHERE ID = 1;

UPDATE TBL_POST
SET POST_CONTENT = '나는 김동건 따위 무섭지 않지'
WHERE ID = 3;

UPDATE TBL_POST
SET POST_CONTENT = '집에 가고 싶다'
WHERE ID = 4;

UPDATE TBL_POST
SET POST_CONTENT = '사실은 공짜야'
WHERE ID = 5;

UPDATE TBL_POST
SET POST_CONTENT = '배고프다'
WHERE ID = 6;

-- 무결성 제약 조건때문에 삭제 안됨 (참조 무결성)
--DELETE FROM TBL_POST
--WHERE ID = 1;

SELECT * FROM TBL_REPLY;

--	김동건이 들어간 게시글 유저의 ID를 가져오기
SELECT ID
FROM TBL_POST
WHERE POST_TITLE LIKE '%김동건%' OR POST_CONTENT LIKE '%김동건%';

--	'김' 씨를 포함하고 있는 게시글 가져오기

SELECT *
FROM TBL_POST
WHERE POST_TITLE LIKE '%김%' OR POST_CONTENT LIKE '%김%';

--	2번 회원이 작성한 게시글 가져오기

SELECT *
FROM TBL_POST
WHERE USER_ID = 2;

-- 2번 문제의 게시물에 댓글들 가져오기

SELECT *
FROM TBL_REPLY 
WHERE POST_ID IN (
	SELECT ID
	FROM TBL_POST
	WHERE POST_TITLE LIKE '%김%' OR POST_CONTENT LIKE '%김%'
);

-- TBL_USER
-- 서울시에 살고 있는 유저의 아이디 가져오기

SELECT ID
FROM TBL_USER
WHERE USER_ADDRESS LIKE '서울시%';

-- TBL_POST
-- 2) 전체 평균 USER_ID 보다 작은 ID를 가진 유저의 게시글 모두 가져오기

SELECT ID, POST_TITLE, POST_CONTENT, POST_CREATE_DATE, USER_ID
FROM TBL_POST 
WHERE USER_ID < (
	SELECT AVG(USER_ID)
	FROM TBL_POST
);

-- 3) 2,3번 유저의 게시글 제목만 가져오기

SELECT POST_TITLE
FROM TBL_POST 
WHERE USER_ID IN (2, 3);

-- 1990년대 ~ 2000년대 생
-- TO_DATE('값', 'YYYY-MM-DD HH24:MI:SS')
-- BETWEEN 작은 시간 AND 큰 시간

SELECT *
FROM TBL_USER
WHERE USER_BIRTH BETWEEN TO_DATE ('1990-01-01', 'YYYY-MM-DD') AND TO_DATE ('2000-01-01', 'YYYY-MM-DD');

-- 시스템의 현재시간을 문자열로 변경 하기
SELECT SYSDATE, CURRENT_DATE , CURRENT_TIMESTAMP FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYYMMDD'), TO_CHAR(CURRENT_DATE, 'YYYY"년"MM"월"DD"일"'), TO_CHAR(CURRENT_TIMESTAMP , 'YYYY')  FROM DUAL;

-- 문자열 함수
SELECT '홍' || '길동' FROM DUAL;
SELECT CONCAT(CONCAT('홍', '길동'), '님') FROM DUAL;
SELECT LENGTH('내가 그린 기린 그림은 잘 그린 기린 그림이다') FROM DUAL; -- 공백문자 포함
SELECT SUBSTR('내가 그린 기린 그림은 잘 그린 기린 그림이다', 1, 8)FROM DUAL;
SELECT UPPER('Apple, Mellon') FROM DUAL;
SELECT LOWER('Apple, Mellon') FROM DUAL;
SELECT REPLACE('내가 그린 기린 그림은 잘 그린 기린 그림이다', '기린', '코끼리') FROM DUAL;
SELECT INSTR('내가 그린 기린 그림은 잘 그린 기린 그림이다', '잘') FROM DUAL;
SELECT REGEXP_REPLACE('내가 그린 기린 그림은 잘 그린 기린 그림이다', '기린', '코끼리', 1, 2) FROM DUAL;

SELECT * FROM TBL_POST;

-- POST를 작성한 시간이 15시 15분 부터 15시 17분 사이에 작성된 게시글만 가져오기

SELECT *
FROM TBL_POST 
WHERE POST_CREATE_DATE BETWEEN '2025-02-25 15:15' AND '2025-02-25 15:20';



