/*
요구사항
   유치원을 하려고 하는데, 아이들이 체험학습 프로그램을 신청해야 합니다.
   아이들 정보는 이름, 나이, 성별이 필요하고 학부모는 이름, 나이, 주소, 전화번호, 성별이 필요해요
   체험학습은 체험학습 제목, 체험학습 내용, 이벤트 이미지 여러 장이 필요합니다.
   아이들은 여러 번 체험학습에 등록할 수 있어요.
*/

CREATE TABLE TBL_PERENT(
	ID NUMBER CONSTRAINT PR_PERENT PRIMARY KEY,
	PERENT_NAME VARCHAR(255),
	PERENT_AGE NUMBER,
	PERENT_ADDRESS VARCHAR(255),
	PERENT_PHONE VARCHAR(255),
	PERENT_GENDER VARCHAR(3000) /**/
)


CREATE TABLE TBL_KIDS(
	ID NUMBER CONSTRAINT PR_KIDS PRIMARY KEY,
	KID_NAME VARCHAR(255),
	KID_AGE NUMBER,
	KID_GENDER VARCHAR(3),
	KID_PERENT_ID NUMBER,
	CONSTRAINT FK_PERENT_ID FOREIGN KEY(KID_PERENT_ID) REFERENCES TBL_PERENT(ID)
);


CREATE TABLE TBL_LERNING(
	ID NUMBER CONSTRAINT PR_LERNING PRIMARY KEY,
	LERNING_TITLE VARCHAR(255),
	LERNING_CONTENTS VARCHAR(255),
	LERNING_KID_ID NUMBER,
	CONSTRAINT FK_KID_ID FOREIGN KEY(LERNING_KID_ID) REFERENCES TBL_KIDS(ID)
);

CREATE TABLE TBL_LERNING_IMAGES(
	ID NUMBER CONSTRAINT PR_IMAGES PRIMARY KEY,
	IMAGES_LERNING_ID NUMBER,
	CONSTRAINT FK_LERNING_ID FOREIGN KEY(IMAGES_LERNING_ID) REFERENCES TBL_LERNING(ID)
);

/*

   요구사항
   안녕하세요, 광고 회사를 운영하려고 준비중인 사업가입니다.
   광고주는 기업이고 기업 정보는 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)입니다.
   광고는 제목, 내용이 있고 기업은 여러 광고를 신청할 수 있습니다.
   기업이 광고를 선택할 때에는 카테고리로 선택하며, 대카테고리, 중카테고리, 소카테고리가 있습니다.

*/
/*
 * 기업
 * 광고
 * 신청
 * 
 * */
-- CHECK(속성 이름 IN('값1', '값2', '값3'))
CREATE TABLE TBL_COMPANY(
	ID NUMBER CONSTRAINT PR_COMPANY PRIMARY KEY,
	COMPANY_NAME VARCHAR2(255),
	COMPANY_ADDRESS VARCHAR2(255),
	COMPANY_PHONE VARCHAR2(255),
	COMPANY_TYPE VARCHAR2(255)
);

CREATE TABLE TBL_ADVERTIZE(
	ID NUMBER,
	ADVERTIZE_CATEGORY VARCHAR2(255),
	ADVERTIZE_TITLE VARCHAR2(255),
	ADVERTIZE_CONTENTS VARCHAR2(255),
	CONSTRAINT PR_ADVERTIZE PRIMARY KEY (ID, ADVERTIZE_CATEGORY)
);

CREATE TABLE TBL_APPLY(
	ID NUMBER CONSTRAINT PR_APPLY PRIMARY KEY,
	COMPANY_ID NUMBER,
	ADVERTIZE_ID NUMBER,
	ADVERTIZE_CATEGORY VARCHAR2(255),
	CONSTRAINT FK_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_ADVERTIZE_ID FOREIGN KEY (ADVERTIZE_ID, ADVERTIZE_CATEGORY) 
	REFERENCES TBL_ADVERTIZE(ID, ADVERTIZE_CATEGORY)
);

/*
 * 설계 
 * 1. 회사
 * 2. 카테고리 대, 중, 소
 * 2-1 대-> 중 -> 소 ID값 보유
 * 3. 광고 (소 카테고리 아이디 포함)
 * 4. 신청
 * 
 * */

CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
   ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
   COMPANY_NAME VARCHAR(255) NOT NULL,
   COMPANY_ADDRESS VARCHAR2(255) NOT NULL,
   COMPANY_TEL VARCHAR2(255),
   COMPANY_TYPE VARCHAR(255) NOT NULL CONSTRAINT BAN_TYPE
   CHECK(COMPANY_TYPE IN ('스타트업', '중소기업', '중견기업','대기업'))
);

CREATE TABLE TBL_CATEGORY_A(
   ID NUMBER CONSTRAINT PK_CATEGORY_A PRIMARY KEY,
   CAREGORY_A_NAME VARCHAR2(255)
);

CREATE TABLE TBL_CATEGORY_B(
   ID NUMBER CONSTRAINT PK_CATEGORY_B PRIMARY KEY,
   CAREGORY_B_NAME VARCHAR2(255),
   CATEGORY_A_ID NUMBER,
   CONSTRAINT FK_CATEGORY_B_CATEGORY_A FOREIGN KEY(CATEGORY_A_ID)
   REFERENCES TBL_CATEGORY_A(ID)
);

CREATE TABLE TBL_CATEGORY_C(
   ID NUMBER CONSTRAINT PK_CATEGORY_C PRIMARY KEY,
   CAREGORY_C_NAME VARCHAR2(255),
   CATEGORY_B_ID NUMBER,
   CONSTRAINT FK_CATEGORY_C_CATEGORY_B FOREIGN KEY(CATEGORY_B_ID)
   REFERENCES TBL_CATEGORY_B(ID)
);

CREATE TABLE TBL_ADVERTISEMENT(
   ID NUMBER CONSTRAINT PK_ADVERTISEMENT PRIMARY KEY,
   ADVERTISEMENT_TITLE VARCHAR2(255) NOT NULL,
   ADVERTISEMENT_CONTENT VARCHAR2(255),
   CATEGORY_C_ID NUMBER,
   CONSTRAINT FK_ADVERTISEMENT_CATEGORY_C FOREIGN KEY(CATEGORY_C_ID)
   REFERENCES TBL_CATEGORY_C(ID)
);

CREATE TABLE TBL_ADVERTISEMENT_APPLY(
   ID NUMBER CONSTRAINT PK_ADVERTISEMENT_APPLY PRIMARY KEY,
   COMPANY_ID NUMBER,
   ADVERTISEMENT_ID NUMBER,
   CONSTRAINT FK_ADVERTISEMENT_APPLY_COMPANY FOREIGN KEY(COMPANY_ID)
   REFERENCES TBL_COMPANY(ID),
   CONSTRAINT FK_ADVERTISEMENT_APPLY_ADVERTISEMENT FOREIGN KEY(ADVERTISEMENT_ID)
   REFERENCES TBL_ADVERTISEMENT(ID)
);

/*
요구사항
이커머스 창업 준비중입니다. 기업과 사용자 간 거래를 위해 기업의 정보와 사용자 정보가 필요합니다.
기업의 정보는 기업 이름, 주소, 대표번호가 있고
사용자 정보는 이름, 주소, 전화번호가 있습니다. 결제 시 사용자 정보와 기업의 정보, 결제한 카드의 정보 모두 필요하며,
상품의 정보도 필요합니다. 상품의 정보는 이름, 가격, 재고입니다.
사용자는 등록한 카드의 정보를 저장할 수 있으며, 카드의 정보는 카드번호, 카드사, 회원 정보가 필요합니다.
*/

/*
 * 기업
 * 사용자
 * 상품
 * 결제
 * 카드
 * 
 * */

CREATE SEQUENCE COMPANY;
CREATE TABLE TBL_COMPANY(
	COMPANY_ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
	COMPANY_NAME VARCHAR2(255),
	COMPANY_ADDRESS VARCHAR2(255),
	COMPANY_TELL VARCHAR2(255)
);

CREATE SEQUENCE GOODS;
CREATE TABLE TBL_GOODS(
	GOODS_ID NUMBER CONSTRAINT PK_GOODS PRIMARY KEY,
	GOODS_NAME VARCHAR2(255),
	GOODS_PRICE NUMBER DEFAULT 0,
	GOODS_STOCK NUMBER DEFAULT 0,
	COMPANY_ID NUMBER,
	CONSTRAINT FK_GOODS_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY
);

CREATE SEQUENCE USERS;
CREATE TABLE TBL_USERS(
	USER_ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255),
	USER_ADDRESS VARCHAR2(255),
	USER_PHONE VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE CARD;
CREATE TABLE TBL_CARD( 
	CARD_NUMBER NUMBER CONSTRAINT PK_CARD PRIMARY KEY,
	CARD_COMPANY VARCHAR2(255),
	USER_ID NUMBER,
	CONSTRAINT FK_CARD_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_USERS
);

CREATE SEQUENCE PAYMENT;
CREATE TABLE TBL_PAYMENT(
	PAYMENT_ID NUMBER CONSTRAINT PK_PAYMENT PRIMARY KEY,
	PAYMENT_GOODS_ID NUMBER,
	PAYMENT_CARD_ID NUMBER,
	CONSTRAINT FK_GOODS_ID FOREIGN KEY(PAYMENT_GOODS_ID)
	REFERENCES TBL_GOODS(GOODS_ID),
	CONSTRAINT FK_CARD_ID FOREIGN KEY(PAYMENT_CARD_ID)
	REFERENCES TBL_CARD(CARD_NUMBER)
);

/*
요구사항
음료수 판매 업체입니다. 음료수마다 당첨번호가 있습니다. 
음료수의 당첨번호는 1개이고 당첨자의 정보를 알아야 상품을 배송할 수 있습니다.
당첨 번호마다 당첨 상품이 있고, 당첨 상품이 배송 중인지 배송 완료인지 구분해야 합니다.
*/

/*
 * 음료수
 * 당첨번호
 * 구매자
 * 당첨자
 * 당첨상품
 * 배송현황
 * 
 * */

CREATE SEQUENCE SEQ_DRINK;
CREATE TABLE TBL_DRINK (
	DRINK_ID NUMBER CONSTRAINT PK_DRINK PRIMARY KEY,
	DRINK_NAME VARCHAR2(255)
);

CREATE SEQUENCE SEQ_BUYER;
CREATE TABLE TBL_BUYER(
	BUYER_ID NUMBER CONSTRAINT PK_BUYER PRIMARY KEY,
	BUYER_NAME VARCHAR2(255),
	BUYER_ADDRESS VARCHAR(255),
	DRINK_ID NUMBER,
	CONSTRAINT FK_DRINK_ID FOREIGN KEY(DRINK_ID)
	REFERENCES TBL_DRINK(DRINK_ID)
);

CREATE SEQUENCE SEQ_PRIZE;
CREATE TABLE TBL_PRIZE(
	PRIZE_ID NUMBER CONSTRAINT PK_PRIZE PRIMARY KEY,
	PRIZE_DRINK NUMBER,
	CONSTRAINT FK_PRIZE_DRINK FOREIGN KEY(PRIZE_DRINK)
	REFERENCES TBL_DRINK(DRINK_ID)
);

CREATE SEQUENCE SEQ_DILIVERY;
CREATE TABLE TBL_DILIVERY(
	DILIVERY_ID NUMBER CONSTRAINT PK_DILIVERY PRIMARY KEY,
	DILIVERY_ISDILEVER VARCHAR(255),
	DILIVERY_PRIZE NUMBER,
	DILIVERY_BUYER NUMBER,
	CONSTRAINT FK_PRIZE_ID FOREIGN KEY(DILIVERY_PRIZE)
	REFERENCES TBL_PRIZE(PRIZE_ID),
	CONSTRAINT FK_BUYER_ID FOREIGN KEY(DILIVERY_BUYER)
	REFERENCES TBL_BUYER(BUYER_ID)
);









