CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255)
);

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 0
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	MEMBER_ID NUMBER,
	PRODUCT_ID NUMBER,
	PRODUCT_COUNT NUMBER DEFAULT 1,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);

SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_PRODUCT;
SELECT * FROM TBL_ORDER;

SELECT 
	TBO.ID, TBO.MEMBER_ID, TBO.PRODUCT_ID, TBO.PRODUCT_COUNT,
	TBM.MEMBER_EMAIL, TBM.MEMBER_NAME,
	TBP.PRODUCT_NAME, TBP.PRODUCT_PRICE,
	TBP.PRODUCT_PRICE * TBO.PRODUCT_COUNT AS TOTAL_PRICE
FROM TBL_ORDER TBO
JOIN TBL_MEMBER TBM
ON TBO.MEMBER_ID = TBM.ID 
JOIN TBL_PRODUCT TBP
ON TBO.PRODUCT_ID = TBP.ID;

SELECT PRODUCT_COUNT
FROM TBL_ORDER
WHERE ID = 1;
