CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 0
);

SELECT * FROM TBL_PRODUCT;

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
WHERE ID = 1;

DELETE FROM TBL_PRODUCT
WHERE ID = 1;

SELECT * 
FROM (
	SELECT ID
	FROM TBL_PRODUCT
	ORDER BY ID DESC
)
WHERE ROWNUM = 1;

UPDATE TBL_PRODUCT
SET PRODUCT_NAME = '수정더미', PRODUCT_PRICE = 100, PRODUCT_STOCK = 50
WHERE ID = 5;

CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL
);

SELECT * FROM TBL_POST;











