-- 자동차
-- 번호, 브랜드, 날짜, 색상, 가격
-- 가격을 재고로 이름 변경
-- 출시날짜 컬럼 추가

CREATE TABLE TBL_CAR(
	ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	CAR_NUMBER NUMBER NOT NULL UNIQUE,
	CAR_BRAND VARCHAR2(255),
	CAR_DAY DATE,
	CAR_COLOR VARCHAR2(255),
	PRODUCT_PRICE NUMBER DEFAULT 0
);

ALTER TABLE TBL_CAR RENAME COLUMN PRODUCT_PRICE TO CAR_STOCK;

ALTER TABLE TBL_CAR ADD CAR_DATE DATE;

SELECT * FROM TBL_CAR;

DROP TABLE TBL_CAR;









-- FK(FOREIGN KEY)
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255),
	USER_AGE NUMBER
);

CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_NAME VARCHAR2(255),
	ORDER_TIME DATE,
	USER_ID NUMBER,
	CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID) REFERENCES TBL_USER(ID)
);








-- 실습
-- 요구사항
-- 회사에서 광고를 신청하려고 합니다.
-- 하나의 회사는 여러개 광고를 신청할 수 있어야 합니다.
-- 회사는 이름과 전화번호를 넣을 수 있는 테이블이 필요합니다.
-- 광고는 광고 이름과 컨텐츠를 넣을 수 있는 테이블이 필요합니다.
DROP TABLE TBL_COMPANY;
CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY (
	ID NUMBER,
	COMPANY_NAME VARCHAR2(255) NOT NULL UNIQUE,
	COMPANY_PHONE VARCHAR2(255),
	CONSTRAINT PK_COMPANY PRIMARY KEY(ID)
);

CREATE SEQUENCE SEQ_ADVERTISE;
CREATE TABLE TBL_ADVERTISE (
	ID NUMBER ,
	ADVERTISE_NAME VARCHAR2(255),
	ADVERTISE_CONTENT VARCHAR2(255),
	COMPANY_ID NUMBER,
	CONSTRAINT PK_ADVERTISE PRIMARY KEY(ID),
	CONSTRAINT FK_ADVERTISE_COMPANY FOREIGN KEY(COMPANY_ID) REFERENCES TBL_COMPANY(ID)
);

-- 요구사항
-- 상품 판매자, 상품 구매자에게 배송할 수 있는 서비스가 필요해요.
-- 판매자 : 음료, 음료 종류, 음료수의 크기, 만든 날짜
-- 구매자 : 이름, 전화번호, 주소
-- 배송 : 구매자 아이디, 판매자의 아이디

CREATE SEQUENCE SEQ_SELLER;
CREATE TABLE TBL_SELLER (
	ID NUMBER,
	SELLER_DRINK VARCHAR2(255) NOT NULL UNIQUE,
	SELLER_DRINK_KIND VARCHAR2(255) NOT NULL,
	SELLER_DRINK_SIZE NUMBER NOT NULL,
	SELLER_DRINK_MADEDATE DATE NOT NULL,
	CONSTRAINT PK_SELLER PRIMARY KEY(ID)
);


CREATE SEQUENCE SEQ_BUYER;
CREATE TABLE TBL_BUYER (
	ID NUMBER,
	BUYER_NAME VARCHAR2(255) NOT NULL,
	BUYER_PHONE VARCHAR2(255) NOT NULL UNIQUE,
	BUYER_ADDRESS VARCHAR2(255) NOT NULL,
	CONSTRAINT PK_BUYER PRIMARY KEY(ID)
);

CREATE SEQUENCE SEQ_DELIVERY;
CREATE TABLE TBL_DELIVERY (
	ID NUMBER,
	SELLER_ID NUMBER NOT NULL,
	BUYER_ID NUMBER NOT NULL,
	CONSTRAINT PK_DELIVERY PRIMARY KEY(ID),
	CONSTRAINT FK_SELLERID FOREIGN KEY(SELLER_ID) REFERENCES TBL_SELLER(ID),
	CONSTRAINT FK_BUYERID FOREIGN KEY(BUYER_ID) REFERENCES TBL_BUYER(ID)
);







