CREATE TABLE TBL_USER (
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255),
	USER_AGE NUMBER,
	USER_ADDRESS VARCHAR2(255)
);

SELECT * FROM TBL_USER;

--	테이블 생성
--	주문번호, 주문한사람, 배송주소

CREATE TABLE TBL_ORDER (
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_NUMBER NUMBER,
	ORDER_USER VARCHAR2(255),
	USER_ADDRESS VARCHAR2(255)
);

SELECT * FROM TBL_ORDER;

--	상품
--	상품이름, 상품 가격 - 디폴트 0, 재고 - 디폴트 0
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL UNIQUE,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_SYOCK NUMBER DEFAULT 0
);

SELECT * FROM TBL_PRODUCT;

--	ALTER (변경)
--	컬럼 추가(ADD)
ALTER TABLE TBL_PRODUCT ADD PRODUCT_DATE TIMESTAMP;

--	컬럼 변경(MODIFY) { 
ALTER TAVLE TBL_PRODUCT MODIFY PRODUCT_DATE DATE;


ALTER TABLE TBL_PRODUCT  RENAME COLUMN PRODUCT_DATE TO PRODUCT_TIME;

--컬럼삭제 ALTER ~ DROPCOLUMN
ALTER TABLE TBL_PRODUCT DROP COLUMN PRODUCT_TIME;

ALTER TABLE TBL_PRODUCT RENAME TO TBL_PRODUCT2;

SELECT * FROM TBL_PRODUCT2;

ALTER TABLE TBL_PRODUCT2 RENAME TO TBL_PRODUCT1;

SELECT * FROM TBL_PRODUCT1;

ALTER TABLE TBL_PRODUCT1 RENAME TO TBL_PRODUCT;

--	삭제 DROP 
DROP TABLE TBL_PRODUCT;

--	TRUNCATE
TRUNCATE TABLE TBL_USER;

SELECT * FROM TBL_ORDER;









