/* 학교 테이블*/
CREATE SEQUENCE SEQ_UNIVERSITY;
CREATE TABLE TBL_UNIVERSITY(
   ID NUMBER CONSTRAINT PK_UNIVERSITY PRIMARY KEY,
   UNIVERSITY_NAME VARCHAR2(255) UNIQUE NOT NULL,
   UNIVERSITY_LOCATION VARCHAR2(255) UNIQUE NOT NULL,
   UNIVERSITY_LOGO_IMG_NAME VARCHAR2(255),
   UNIVERSITY_LOGO_IMG_PATH VARCHAR2(255)
);

/* 학과 테이블*/
CREATE SEQUENCE SEQ_MAJOR;
CREATE TABLE TBL_MAJOR(
   ID NUMBER CONSTRAINT PK_MAJOR PRIMARY KEY,
   UNIVERSITY_ID NUMBER NOT NULL,
   MAJOR_NAME VARCHAR2(255) NOT NULL,
   CONSTRAINT FK_MAJOR_UNIVERSITY FOREIGN KEY(UNIVERSITY_ID)
   REFERENCES TBL_UNIVERSITY(ID)
);

/* 회원 테이블*/
CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
   USER_IMG_NAME VARCHAR2(255),
   USER_IMG_PATH VARCHAR2(255),
   USER_NAME VARCHAR2(255) NOT NULL,
   USER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
   USER_ID VARCHAR2(255) UNIQUE NOT NULL,
   USER_PASSWORD VARCHAR2(255) NOT NULL,
   USER_PHONE VARCHAR2(255) UNIQUE NOT NULL,
   USER_NICKNAME VARCHAR2(255),
   USER_ADDRESS VARCHAR2(255),
   USER_POSTAL_CODE VARCHAR2(255) NOT NULL,
   /* BOOLEAN타입 변경*/
   USER_SNS_OK NUMBER(1) DEFAULT 0 NOT NULL,
   USER_MAIL_OK NUMBER(1) DEFAULT 0 NOT NULL,
   USER_AGREEMENT_OK NUMBER(1) DEFAULT 0 NOT NULL,
   USER_INTRODUCE VARCHAR2(500 CHAR) NULL,
   USER_RECODE VARCHAR2(500 CHAR) NULL,
   USER_INSTAGRAM VARCHAR2(255) NULL,
   USER_YOUTUBE VARCHAR2(255) NULL,
   USER_BLOG VARCHAR2(255) NULL,
   USER_KAKAO VARCHAR2(255) NULL,
   USER_GOOGLE VARCHAR2(255) NULL,
   USER_NAVER VARCHAR2(255) NULL,
   /* BOOLEAN타입 변경*/
   USER_WRITER_OK NUMBER(1) DEFAULT 0 NOT NULL,
   USER_ADMIN_OK NUMBER(1) DEFAULT 0 NOT NULL,
   USER_BAN_OK NUMBER(1) DEFAULT 0 NOT NULL,
   UNIVERSITY_ID NUMBER NOT NULL,
   CONSTRAINT FK_USER_UNIVERSITY FOREIGN KEY(UNIVERSITY_ID)
   REFERENCES TBL_UNIVERSITY(ID)
);

/* 작품 정보 테이블*/
CREATE SEQUENCE SEQ_ART;
CREATE TABLE TBL_ART(
   ID NUMBER CONSTRAINT PK_ART PRIMARY KEY,
   ART_CATEGORY VARCHAR2(255) NOT NULL,
   ART_MATERIAL VARCHAR2(255) NOT NULL,
   ART_SIZE VARCHAR2(255) NOT NULL,
   ART_DESCRIPTION VARCHAR2(255) NOT NULL,
   ART_DATE DATE NOT NULL,
   ART_START_DATE DATE NOT NULL,
   ART_END_DATE DATE NOT NULL,
   USER_ID NUMBER NOT NULL,
   CONSTRAINT FK_ART_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID)
);

/* 작품 좋아요 테이블*/
CREATE SEQUENCE SEQ_ART_LIKE;
CREATE TABLE TBL_ART_LIKE(
   ID NUMBER CONSTRAINT PK_ART_LIKE PRIMARY KEY,
   ART_ID NUMBER NOT NULL,
   USER_ID NUMBER NOT NULL,
   ART_LIKE_TIME TIMESTAMP NOT NULL,
   CONSTRAINT FK_ART_LIKE_ART FOREIGN KEY(ART_ID)
   REFERENCES TBL_ART(ID),
   CONSTRAINT FK_ART_LIKE_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID)
);

/* 작품 이미지 테이블 */
CREATE SEQUENCE SEQ_ART_IMG;
CREATE TABLE TBL_ART_IMG(
   ID NUMBER CONSTRAINT PK_ART_IMG PRIMARY KEY,
   ART_IMG_NAME VARCHAR(255) NOT NULL,
   ART_IMG_PATH VARCHAR(255) NOT NULL,
   ART_ID NUMBER NOT NULL,
   CONSTRAINT FK_ART_IMG_ART FOREIGN KEY(ART_ID)
   REFERENCES TBL_ART(ID)
);

/* 그라데이션 전시회 테이블*/
CREATE SEQUENCE SEQ_GRADATION_EXHIBITION;
CREATE TABLE TBL_GRADATION_EXHIBITION(
   ID NUMBER CONSTRAINT PK_GRADATION_EXHIBITION PRIMARY KEY,
   GRADATION_EXHIBITION_TITLE VARCHAR2(255) NOT NULL,
   GRADATION_EXHIBITION_COUNT NUMBER NOT NULL,
   GRADATION_EXHIBITION_TIME DATE NOT NULL,
   GRADATION_EXHIBITION_FEE NUMBER NOT NULL,
   GRADATION_EXHIBITION_TEL VARCHAR2(255) NOT NULL,
   GRADATION_EXHIBITION_ADDRESS VARCHAR2(255) NOT NULL,
   GRADATION_EXHIBITION_DATE DATE NOT NULL
);

/* 학교 전시회 테이블*/
CREATE SEQUENCE SEQ_UNIVERSITY_EXHIBITION;
CREATE TABLE TBL_UNIVERSITY_EXHIBITION(
   ID NUMBER CONSTRAINT PK_UNIVERSITY_EXHIBITION PRIMARY KEY,
   UNIVERSITY_EXHIBITION_DATE DATE NOT NULL,
   UNIVERSITY_EXHIBITION_STATE VARCHAR2(255) NOT NULL,
   UNIVERSITY_EXHIBITION_TITLE VARCHAR2(255) NOT NULL,
   UNIVERSITY_EXHIBITION_LOCATION VARCHAR2(255) NOT NULL,
   MAJOR_ID NUMBER NOT NULL,
   CONSTRAINT FK_UNIVERSITY_EXHIBITION_MAJOR FOREIGN KEY(MAJOR_ID)
   REFERENCES TBL_MAJOR(ID)
);

/* 학교 좋아요 테이블*/
CREATE SEQUENCE SEQ_UNIVERSITY_LIKE;
CREATE TABLE TBL_UNIVERSITY_LIKE(
   ID NUMBER CONSTRAINT PK_UNIVERSITY_LIKE PRIMARY KEY,
   UNIVERSITY_ID NUMBER NOT NULL,
   USER_ID NUMBER NOT NULL,
   UNIVERSITY_LIKE_TIME TIMESTAMP NOT NULL,
   CONSTRAINT FK_UNIVERSITY_LIKE_UNIVERSITY FOREIGN KEY(UNIVERSITY_ID)
   REFERENCES TBL_UNIVERSITY(ID),
   CONSTRAINT FK_UNIVERSITY_LIKE_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID)
);

/* 작품 게시 테이블*/
CREATE SEQUENCE SEQ_ART_POST;
CREATE TABLE TBL_ART_POST(
   ID NUMBER CONSTRAINT PK_ART_POST PRIMARY KEY,
   ART_POST_DATE TIMESTAMP,
   USER_ID NUMBER NOT NULL,
   ART_ID NUMBER NOT NULL,
   CONSTRAINT FK_ART_POST_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID),
   CONSTRAINT FK_ART_POST_ART FOREIGN KEY(ART_ID)
   REFERENCES TBL_ART(ID)
);

/* 게시물 댓글 테이블*/
CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
   ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
   ART_POST_ID NUMBER NOT NULL,
   USER_ID NUMBER NOT NULL,
   REPLY_CONTENTS VARCHAR2(500 CHAR) NOT NULL,
   REPLY_DATE TIMESTAMP,
   CONSTRAINT FK_REPLY_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID),
   CONSTRAINT FK_REPLY_ART_POST FOREIGN KEY(ART_POST_ID)
   REFERENCES TBL_ART_POST(ID)
);

/* 댓글 좋아요 테이블*/
CREATE SEQUENCE SEQ_REPLY_LIKE;
CREATE TABLE TBL_REPLY_LIKE(
   ID NUMBER CONSTRAINT PK_REPLY_LIKE PRIMARY KEY,
   REPLY_ID NUMBER NOT NULL,
   USER_ID NUMBER NOT NULL,
   REPLY_LIKE_TIME TIMESTAMP,
   CONSTRAINT FK_REPLY_LIKE_REPLY FOREIGN KEY(REPLY_ID)
   REFERENCES TBL_REPLY(ID),
   CONSTRAINT FK_REPLY_LIKE_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID)
);

/* 쪽지 테이블*/
CREATE SEQUENCE SEQ_MAIL;
CREATE TABLE TBL_MAIL(
   ID NUMBER CONSTRAINT PK_MAIL PRIMARY KEY,
   MAIL_TITLE VARCHAR2(255) NOT NULL,
   /* ERD 내 CONTENTS 오타 수정 필요*/
   MAIL_CONTENTS VARCHAR2(500 CHAR) NOT NULL,
   MAIL_SEND_TIME TIMESTAMP NOT NULL,
   /* BOOLEAN타입 변경*/
   MAIL_ISOPEN NUMBER(1) DEFAULT 0 NOT NULL,
   SEND_USER_ID NUMBER NOT NULL,
   RECIEVE_USER_ID NUMBER NOT NULL,
   CONSTRAINT FK_MAIL_SEND_USER FOREIGN KEY(SEND_USER_ID)
   REFERENCES TBL_USER(ID),
   CONSTRAINT FK_MAIL_RECIEVE_USER FOREIGN KEY(RECIEVE_USER_ID)
   REFERENCES TBL_USER(ID)
);

/* 경매 테이블*/
CREATE SEQUENCE SEQ_AUCTION;
CREATE TABLE TBL_AUCTION(
   ID NUMBER CONSTRAINT PK_AUCTION PRIMARY KEY,
   ART_ID NUMBER NOT NULL,
   USER_ID NUMBER NOT NULL,
   AUCTION_START_DATE DATE NOT NULL,
   AUCTION_START_PRICE NUMBER NOT NULL,
   AUCTION_ESTIMATED_PRICE NUMBER NOT NULL,
   /* BOOLEAN타입 변경*/
   AUCTION_ATTRACTED NUMBER(1) DEFAULT 0 NOT NULL,
   AUCTION_BID_PRICE NUMBER,
   AUCTION_BID_DATE DATE,
   CONSTRAINT FK_AUCTION_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID),
   CONSTRAINT FK_AUCTION_ART FOREIGN KEY(ART_ID)
   REFERENCES TBL_ART(ID)
);

/* 결제 테이블*/
CREATE SEQUENCE SEQ_PAYMENT;
CREATE TABLE TBL_PAYMENT(
   ID NUMBER CONSTRAINT PK_PAYMENT PRIMARY KEY,
   AUCTION_ID NUMBER NOT NULL,
   PAYMENT_METHOD VARCHAR2(255) NOT NULL,
   PAYMENT_AMOUNT NUMBER NOT NULL,
   PAYMENT_DATE TIMESTAMP NOT NULL,
   PAYMENT_CODE VARCHAR2(255) NOT NULL,
   CONSTRAINT FK_PAYMENT_AUCTION FOREIGN KEY(AUCTION_ID)
   REFERENCES TBL_AUCTION(ID)
);

/* 결제 취소 테이블*/
CREATE SEQUENCE SEQ_PAYMENT_CANCELLATION;
CREATE TABLE TBL_PAYMENT_CANCELLATION(
   ID NUMBER CONSTRAINT PK_PAYMENT_CANCELLATION PRIMARY KEY,
   PAYMENT_CANCELLATION_CODE VARCHAR2(255) NOT NULL,
   PAYMENT_ID NUMBER NOT NULL,
   CONSTRAINT FK_PAYMENT_CANCELLATION_PAYMENT FOREIGN KEY(PAYMENT_ID)
   REFERENCES TBL_PAYMENT(ID)
);


/* 배송 테이블*/
CREATE SEQUENCE SEQ_DELIVERY;
CREATE TABLE TBL_DELIVERY(
   ID NUMBER CONSTRAINT PK_DELIVERY PRIMARY KEY,
   DELIVERY_ADDRESS VARCHAR2(255),
   DELIVERY_DETAIL_ADDRESS VARCHAR2(255),
   DELIVERY_POSTAL_CODE VARCHAR2(255),
   DELIVERY_STATE VARCHAR2(255) NOT NULL,
   DELIVERY_MESSAGE VARCHAR2(255),
   DELIVERY_RECEIVER VARCHAR2(255) NOT NULL,
   DELIVERY_PHONE VARCHAR2(255) NOT NULL,
   PAYMENT_ID NUMBER NOT NULL,
   CONSTRAINT FK_DELIVERY_PAYMENT FOREIGN KEY(PAYMENT_ID)
   REFERENCES TBL_PAYMENT(ID)   
);

/* 유저 정지 테이블*/
CREATE SEQUENCE SEQ_BAN;
CREATE TABLE TBL_BAN(
   ID NUMBER CONSTRAINT PK_BAN PRIMARY KEY,
   BAN_REASON VARCHAR2(255) NOT NULL,
   BAN_DATE TIMESTAMP NOT NULL,
   USER_ID NUMBER NOT NULL,
   CONSTRAINT FK_BAN_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID)
);

/* 업사이클링 신청 테이블*/
CREATE SEQUENCE SEQ_UPCYCLE;
CREATE TABLE TBL_UPCYCLE(
   ID NUMBER CONSTRAINT PK_JOIN_UPCYCLE PRIMARY KEY,
   UPCYCLE_CATEGORY VARCHAR2(255) NOT NULL,
   UPCYCLE_SIZE VARCHAR2(255) NOT NULL,
   UPCYCLE_DATE DATE NOT NULL,
   UPCYCLE_ADDRESS VARCHAR2(255) NOT NULL,
   USER_ID NUMBER NOT NULL,
   CONSTRAINT FK_UPCYCLE_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID)
);

/* 1대1 문의 테이블*/
CREATE SEQUENCE SEQ_QNA;
CREATE TABLE TBL_QNA(
   ID NUMBER CONSTRAINT PK_QNA PRIMARY KEY,
   QNA_TITLE VARCHAR2(255) NOT NULL,
   QNA_CONTENT VARCHAR2(255) NOT NULL,
   QNA_TIME TIMESTAMP NOT NULL,
   QNA_IMG_NAME VARCHAR2(255),
   QNA_IMG_PATH VARCHAR2(255),
   USER_ID NUMBER NOT NULL,
   CONSTRAINT FK_QNA_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID)
);

/* 1대1 문의답변 테이블*/
CREATE SEQUENCE SEQ_QNA_ANSWER;
CREATE TABLE TBL_QNA_ANSWER(
   ID NUMBER CONSTRAINT PK_QNA_ANSWER PRIMARY KEY,
   QNA_ANSWER_TITLE VARCHAR2(255) NOT NULL,
   QNA_ANSWER_CONTENT VARCHAR2(255) NOT NULL,
   QNA_ANSWER_TIME TIMESTAMP NOT NULL,
   QNA_ID NUMBER NOT NULL,
   CONSTRAINT FK_QNA_ANSWER_QNA FOREIGN KEY(QNA_ID)
   REFERENCES TBL_QNA(ID)
);

/* 자주 묻는 질문 테이블*/
CREATE SEQUENCE SEQ_FAQ;
CREATE TABLE TBL_FAQ(
   ID NUMBER CONSTRAINT PK_FAQ PRIMARY KEY,
   FAQ_TITLE VARCHAR2(255) NOT NULL,
   FAQ_CONTENT VARCHAR2(500 CHAR) NOT NULL
);
