CREATE SEQUENCE SEQ_BUY_USER;
CREATE TABLE TBL_BUY_USER(
   ID NUMBER CONSTRAINT PK_BUYER_USER PRIMARY KEY,
   BUY_USER_NAME VARCHAR(255) NOT NULL,
   BUY_USER_AGE NUMBER,
   BUY_USER_GENDER CHAR(10) NOT NULL,
   BUY_USER_PHONE VARCHAR2(255)
);

ALTER TABLE TBL_BUY_USER ADD BUY_USER_ADDRESS VARCHAR2(255); 

--ALTER TABLE TBL_BUYER_USER MODIFY BUY_USER_GENDER CHAR(5);

CREATE SEQUENCE SEQ_SELL_PRODUCT;
CREATE TABLE TBL_SELL_PRODUCT(
   ID NUMBER CONSTRAINT PK_SELL_PRODUCT PRIMARY KEY,
   SELL_PRODUCT_BRAND VARCHAR2(255) NOT NULL,
   SELL_PRODUCT_NAME VARCHAR(255),
   SELL_PRODUCT_PRICE NUMBER DEFAULT 0,
   SELL_PRODUCT_DELIVERY NUMBER,
   SELL_PRODUCT_STOCK NUMBER DEFAULT 0
);

CREATE SEQUENCE SEQ_PRODUCT_ORDER;
CREATE TABLE TBL_PRODUCT_ORDER(
   ID NUMBER CONSTRAINT PK_PRODUCT_ORDRER PRIMARY KEY,
   BUY_USER_ID NUMBER,
   SELL_PRODUCT_ID NUMBER,
   CONSTRAINT FK_PRODUCT_ORDER_BUY_USER FOREIGN KEY(BUY_USER_ID)
   REFERENCES TBL_BUY_USER,
   CONSTRAINT FK_PRODUCT_ORDER_SELL_PRODUCT FOREIGN KEY(SELL_PRODUCT_ID)
   REFERENCES TBL_SELL_PRODUCT
);

INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '홍길동', 20, '남', '01044872828', '서울시 강남구');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '이순신', 30, '남', '01044477224', '경기도 구리시');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '김철수', 40, '남', '01022774277', '경기도 분당시');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '김영희', 20, '여', '01032155459', '서울시 중랑구');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '이아영', 30, '여', '01044225789', '경기도 수원시');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '정유리', 40, '여', '01042837612', '서울시 종로구');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '최성진', 20, '남', '01047275591', '서울시 강남구');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '조사랑', 30, '여', '01024772332', '서울시 강서구');
INSERT INTO TBL_BUY_USER
VALUES(SEQ_BUY_USER.NEXTVAL, '강민구', 10, '남', '01038453841', '경기도 분당시');

SELECT * FROM TBL_BUY_USER;

INSERT INTO TBL_SELL_PRODUCT
VALUES (SEQ_SELL_PRODUCT.NEXTVAL, '무신사', '라운드 티셔츠', 25300, 5, 50);

INSERT INTO TBL_SELL_PRODUCT
VALUES (SEQ_SELL_PRODUCT.NEXTVAL, '아디다스', '스니커즈', 150000, 7, 200);

INSERT INTO TBL_SELL_PRODUCT
VALUES (SEQ_SELL_PRODUCT.NEXTVAL, '톰브라운', '블레이저 재킷', 1600000, 20, 100);

INSERT INTO TBL_SELL_PRODUCT
VALUES (SEQ_SELL_PRODUCT.NEXTVAL, '닥터마틴', '버지니아', 260000, 3, 50);

INSERT INTO TBL_SELL_PRODUCT
VALUES (SEQ_SELL_PRODUCT.NEXTVAL, '플로랄프로렌', '슬립 티셔츠', 500000, 10, 200);

INSERT INTO TBL_SELL_PRODUCT
VALUES (SEQ_SELL_PRODUCT.NEXTVAL, '예일', '반팔 티셔츠', 27300, 1, 1000);

INSERT INTO TBL_SELL_PRODUCT
VALUES (SEQ_SELL_PRODUCT.NEXTVAL, '컨버스', '척 클래식', 90000, 4, 10);

INSERT INTO TBL_SELL_PRODUCT
VALUES (SEQ_SELL_PRODUCT.NEXTVAL, '버버리', '코튼 볼캡', 318000, 20, 40);

INSERT INTO TBL_SELL_PRODUCT
VALUES (SEQ_SELL_PRODUCT.NEXTVAL, '스파오', '옥스포드 셔츠', 32300, 2, 50);

-- 주문 데이터
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 2, 1);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 2, 7);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 2, 6);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 3, 3);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 2, 6);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 4, 6);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 4, 5);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 4, 8);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 5, 1);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 5, 2);

INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 5, 9);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 5, 6);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 5, 5);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 6, 1);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 6, 5);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 6, 8);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 7, 7);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 7, 2);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 7, 3);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 8, 1);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 8, 4);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 8, 5);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 8, 6);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 8, 8);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 9, 9);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 9, 5);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 9, 3);
INSERT INTO TBL_PRODUCT_ORDER
VALUES (SEQ_PRODUCT_ORDER.NEXTVAL, 9, 2);

SELECT * FROM TBL_BUY_USER tbu ;
SELECT * FROM TBL_PRODUCT_ORDER tpo  ;
SELECT * FROM TBL_SELL_PRODUCT tsp  ;

SELECT SYSDATE FROM DUAL;

-- 가장 자격이 비싼 상품정보 1개를 조회

-- WHERE ROWNUM = 행의 개수
SELECT *
FROM (
	SELECT  * 
	FROM TBL_SELL_PRODUCT
	ORDER BY SELL_PRODUCT_PRICE DESC
)
WHERE ROWNUM = 1;

-- 1) 30대가 구매한 상품중에 가장 비났ㄴ 상품의 이름 1개를 조회하기

SELECT SELL_PRODUCT_NAME 
FROM (
	SELECT *
	FROM (
		SELECT  * 
		FROM TBL_PRODUCT_ORDER TPO
		JOIN (
			SELECT ID
			FROM TBL_BUY_USER
			WHERE BUY_USER_AGE = 30
		) TBU
		ON TBU.ID = TPO.BUY_USER_ID
	) TBU2
	JOIN TBL_SELL_PRODUCT TSP 
	ON TSP.ID = TBU2.SELL_PRODUCT_ID
	ORDER BY SELL_PRODUCT_PRICE DESC
)
WHERE ROWNUM = 1;

SELECT SELL_PRODUCT_NAME 
FROM(
	SELECT *
	FROM TBL_PRODUCT_ORDER TP
	JOIN TBL_BUY_USER TB
	ON TP.BUY_USER_ID = TB.ID AND TB.BUY_USER_AGE = 30
	JOIN TBL_SELL_PRODUCT TS 
	ON TP.SELL_PRODUCT_ID = TS.ID
	ORDER BY TS.SELL_PRODUCT_PRICE DESC
)
WHERE ROWNUM = 1;

--------------------------------------------------------------
--2) 브랜드 중 무신사를 구매한 20살 수
SELECT COUNT(TBU.ID) AS "무신사를 구매한 20살의 수"
FROM (
	SELECT *
	FROM TBL_SELL_PRODUCT
	WHERE SELL_PRODUCT_BRAND LIKE '%무신사%'
) TSP
JOIN TBL_PRODUCT_ORDER TPO
ON TSP.ID = TPO.SELL_PRODUCT_ID 
JOIN TBL_BUY_USER TBU 
ON TBU.ID = TPO.BUY_USER_ID AND TBU.BUY_USER_AGE = '20';



SELECT TSP.*
FROM (
	SELECT SELL_PRODUCT_ID, COUNT(SELL_PRODUCT_ID) 
	FROM TBL_PRODUCT_ORDER
	GROUP BY SELL_PRODUCT_ID
	HAVING COUNT(SELL_PRODUCT_ID) = (
		SELECT MAX(CNT) 
		FROM (
			SELECT SELL_PRODUCT_ID, COUNT(SELL_PRODUCT_ID) AS CNT
			FROM TBL_PRODUCT_ORDER
			GROUP BY SELL_PRODUCT_ID
			ORDER BY CNT DESC
		)
	)
) TPO
JOIN TBL_SELL_PRODUCT TSP 
ON TPO.SELL_PRODUCT_ID = TSP.ID;

-- 3) 제일 주문이 많이 들어온 상품 정보 조회
SELECT *
FROM TBL_SELL_PRODUCT
WHERE ID IN (
   SELECT SELL_PRODUCT_ID
   FROM (
      SELECT SELL_PRODUCT_ID
      FROM TBL_PRODUCT_ORDER
      GROUP BY SELL_PRODUCT_ID
      ORDER BY COUNT(SELL_PRODUCT_ID) DESC
   ) 
   WHERE ROWNUM = 1 OR ROWNUM = 2
);

-- 연령대별 구매한 금액 조회
SELECT TBU.BUY_USER_AGE, SUM(TSP.SELL_PRODUCT_PRICE) 
FROM TBL_PRODUCT_ORDER TPO
JOIN TBL_SELL_PRODUCT TSP 
ON TPO.SELL_PRODUCT_ID = TSP.ID
JOIN TBL_BUY_USER TBU 
ON TPO.BUY_USER_ID = TBU.ID 
GROUP BY TBU.BUY_USER_AGE 
ORDER BY TBU.BUY_USER_AGE;

--예일 브랜드의 반팔티셔츠의 현재 재고 구하기
SELECT * FROM TBL_SELL_PRODUCT tsp ;
SELECT * FROM TBL_PRODUCT_ORDER tpo ;



SELECT
(
	SELECT SELL_PRODUCT_STOCK 
	FROM TBL_SELL_PRODUCT  
	WHERE SELL_PRODUCT_BRAND = '예일'
) - (
	SELECT COUNT(ID)
	FROM TBL_PRODUCT_ORDER TPO
	WHERE SELL_PRODUCT_ID = (
		SELECT ID FROM TBL_SELL_PRODUCT WHERE SELL_PRODUCT_BRAND = '예일'
	)
) AS "예일 티셔츠 남은 재고"
FROM DUAL;














