SELECT * FROM DUAL;

CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(255) UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255),
	MEMBER_ADDRESS VARCHAR2(255),
	MEMBER_RECOMMENDER_ID VARCHAR2(255)
);

SELECT * FROM TBL_MEMBER;

